version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:lts
jobs:
  build:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependence
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Deploy to gh-pages
          command: |
            git config --global user.email ${GH_EMAIL}
            git config --global user.name ${GH_NAME}
            rm -rf node_modules/gh-pages/.cache
            npx gh-pages -d dist -r https://github.com/ddiu8081/ChartFun.git -b gh-pages -m "auto commit ${CIRCLE_SHA1} [ci skip]"
workflows:
   version: 2
   build_and_deploy:
      jobs:
        - build:
            filters:
              branches:
                only: master